import type { WorkoutDay } from '@/types'

export const WORKOUT_DAYS: WorkoutDay[] = [
  {
    day: 'terca',
    label: 'Tuesday',
    split: 'Push',
    muscles: 'Chest · Shoulders · Triceps',
    exercises: [
      {
        key: 'supino_reto',
        name: 'Chest Press Machine',
        muscle: 'Chest',
        description: 'Adjust seat so handles align with mid-chest. Press forward until arms are fully extended, return with control.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Squeeze chest at full extension',
      },
      {
        key: 'desenvolvimento_halteres',
        name: 'Machine Shoulder Press',
        muscle: 'Shoulders',
        description: 'Adjust seat so handles are at shoulder height. Press overhead until arms are extended. Lower with control — don\'t let the weight stack touch.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Keep back flat against pad',
      },
      {
        key: 'crucifixo_inclinado',
        name: 'Pec Deck Fly',
        muscle: 'Chest',
        description: 'Sit with back flat against pad, forearms on the arm pads. Bring arms together in a hugging motion. Control the return slowly.',
        imageUrl: '',
        tips: '3 × 12–15 reps · Feel the stretch on the way back',
      },
      {
        key: 'elevacao_lateral',
        name: 'Cable Lateral Raise',
        muscle: 'Side Delts',
        description: 'Stand beside cable machine, handle in outside hand at hip. Raise arm out to shoulder level with slight elbow bend. Lower slowly.',
        imageUrl: '',
        tips: '4 × 15 reps per side · 3-second negative',
      },
      {
        key: 'dips',
        name: 'Assisted Dip Machine',
        muscle: 'Chest / Triceps',
        description: 'Set counterweight, grip handles and lower chest toward bars. Lean slightly forward to target chest. Press back up fully.',
        imageUrl: '',
        tips: '3 × 10–12 reps · Reduce counterweight over time',
      },
      {
        key: 'triceps_corda',
        name: 'Tricep Rope Pushdown',
        muscle: 'Triceps',
        description: 'Cable machine with rope attachment, elbows pinned to sides. Push rope down and flare hands apart at the bottom. Control the return.',
        imageUrl: '',
        tips: '4 × 12–15 reps · Elbows stay locked at your sides',
      },
    ],
  },
  {
    day: 'quarta',
    label: 'Wednesday',
    split: 'Legs',
    muscles: 'Quads · Glutes · Hamstrings · Calves',
    exercises: [
      {
        key: 'leg_press',
        name: 'Leg Press',
        muscle: 'Quads / Glutes',
        description: 'Feet shoulder-width on platform. Lower sled until knees reach 90°, press back up without locking knees at the top.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Higher foot = more glutes',
      },
      {
        key: 'agachamento',
        name: 'Smith Machine Squat',
        muscle: 'Quads / Glutes',
        description: 'Bar on upper traps, feet slightly in front of bar. Squat until thighs are parallel, keeping chest up. Press through heels to stand.',
        imageUrl: '',
        tips: '4 × 8–10 reps · Feet slightly forward of bar',
      },
      {
        key: 'extensora',
        name: 'Leg Extension',
        muscle: 'Quads',
        description: 'Adjust seat so knees align with machine pivot. Extend fully and hold 1 second at the top. Lower slowly — 3 count.',
        imageUrl: '',
        tips: '3 × 12–15 reps · Pause at the top',
      },
      {
        key: 'flexora',
        name: 'Lying Leg Curl',
        muscle: 'Hamstrings',
        description: 'Lying face down, adjust pad above heels. Curl until heels approach glutes. Keep hips pressed into pad throughout.',
        imageUrl: '',
        tips: '4 × 12 reps · Hips stay flat on pad',
      },
      {
        key: 'stiff',
        name: 'Hip Abductor Machine',
        muscle: 'Glutes / Hip',
        description: 'Sit with legs together against the outer pads. Push legs apart against resistance. Return slowly — feel the stretch on the way in.',
        imageUrl: '',
        tips: '3 × 15–20 reps · Full range of motion',
      },
      {
        key: 'panturrilha',
        name: 'Seated Calf Raise',
        muscle: 'Calves',
        description: 'Pads on thighs, balls of feet on platform edge. Rise onto toes as high as possible, hold 1–2 sec. Lower until full stretch.',
        imageUrl: '',
        tips: '4 × 15–20 reps · Full stretch at the bottom',
      },
    ],
  },
  {
    day: 'quinta',
    label: 'Thursday',
    split: 'Pull',
    muscles: 'Back · Lats · Biceps',
    exercises: [
      {
        key: 'barra_fixa',
        name: 'Lat Pulldown',
        muscle: 'Lats',
        description: 'Wide overhand grip. Pull bar down to chin with slight backward lean, driving elbows toward hips. Return until arms fully extend.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Pull with your back, not arms',
      },
      {
        key: 'remada_curvada',
        name: 'Seated Cable Row',
        muscle: 'Mid Back',
        description: 'Sit upright, feet on platform, slight knee bend. Pull handle to lower abdomen squeezing shoulder blades. Extend arms fully each rep.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Don\'t round on the stretch',
      },
      {
        key: 'puxada_frontal',
        name: 'Face Pull',
        muscle: 'Rear Delts / Upper Back',
        description: 'Cable at face height with rope. Pull rope toward face separating hands at the end. Elbows stay high and wide throughout.',
        imageUrl: '',
        tips: '4 × 15 reps · Essential for shoulder health',
      },
      {
        key: 'remada_unilateral',
        name: 'Chest Supported Row Machine',
        muscle: 'Back',
        description: 'Chest rests on angled pad, neutral grip on handles. Pull handles back squeezing shoulder blades. Supported chest removes lower back stress.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Full stretch every rep',
      },
      {
        key: 'rosca_direta',
        name: 'Cable Bicep Curl',
        muscle: 'Biceps',
        description: 'Low cable with straight or EZ-bar attachment. Elbows pinned to sides. Curl up and squeeze at top, lower fully for complete stretch.',
        imageUrl: '',
        tips: '3 × 12 reps · Constant tension vs free weights',
      },
      {
        key: 'rosca_martelo',
        name: 'Rope Hammer Curl',
        muscle: 'Biceps / Forearm',
        description: 'Low cable with rope, neutral grip (thumbs up). Curl both handles to shoulder height simultaneously. Lower with control.',
        imageUrl: '',
        tips: '3 × 12 reps · Builds arm thickness',
      },
    ],
  },
]

export const DAYS_MAP: Record<string, WorkoutDay> = Object.fromEntries(
  WORKOUT_DAYS.map((d) => [d.day, d])
)

export const MOTIVATIONAL_PHRASES = [
  'O único treino ruim é o que não aconteceu.',
  'Consistência bate perfeição toda vez.',
  'Seu eu do futuro vai te agradecer.',
  'Sem atalhos. Só o treino de hoje.',
  'Mais pesado que ontem.',
  'A dor passa. O orgulho fica.',
  'Seja a pessoa mais forte da sala.',
  'Foco. Força. Dedicação.',
  'Levanta mais do que as suas desculpas.',
  'Todo dia é dia de treinar a mentalidade.',
  'Pequenos progressos ainda são progressos.',
  'A academia não te abandona se você não abandonar ela.',
  'Dói agora, orgulha depois.',
  'Não pare quando estiver cansado. Pare quando terminar.',
  'A mudança começa onde o conforto termina.',
]
