import type { WorkoutDay } from '@/types'

const WGER = 'https://wger.de/media/exercise-images'

export const WORKOUT_DAYS: WorkoutDay[] = [
  {
    day: 'terca',
    label: 'Tuesday',
    split: 'Push',
    muscles: 'Chest · Shoulders · Triceps',
    exercises: [
      {
        key: 'supino_reto',
        name: 'Barbell Bench Press',
        muscle: 'Chest',
        description: 'Lie flat on bench, grip bar slightly wider than shoulder-width. Lower to chest, press up fully. Keep feet flat and back neutral.',
        imageUrl: `${WGER}/192/Bench-press-1.png`,
        tips: '4 × 8–10 reps · Elbows at 45° from torso',
      },
      {
        key: 'desenvolvimento_halteres',
        name: 'Dumbbell Shoulder Press',
        muscle: 'Shoulders',
        description: 'Seated or standing, hold dumbbells at shoulder height. Press overhead until arms are fully extended. Lower with control.',
        imageUrl: `${WGER}/123/dumbbell-shoulder-press-large-1.png`,
        tips: '4 × 10–12 reps · Keep core tight throughout',
      },
      {
        key: 'crucifixo_inclinado',
        name: 'Incline Dumbbell Fly',
        muscle: 'Upper Chest',
        description: 'Set bench to 30–45°. With slight elbow bend, open arms wide and lower dumbbells in an arc. Squeeze chest at the top.',
        imageUrl: `${WGER}/122/Incline-cable-flyes-1.png`,
        tips: '3 × 12 reps · Think "hugging a barrel"',
      },
      {
        key: 'elevacao_lateral',
        name: 'Dumbbell Lateral Raise',
        muscle: 'Side Delts',
        description: 'Stand with dumbbells at sides. Raise laterally to shoulder height with slight elbow bend. Lower slowly (3 seconds).',
        imageUrl: `${WGER}/148/lateral-dumbbell-raises-large-2.png`,
        tips: '4 × 15 reps · Slow eccentric = more gains',
      },
      {
        key: 'dips',
        name: 'Chest Dip',
        muscle: 'Chest / Triceps',
        description: 'On parallel bars, lean torso slightly forward. Lower until arms are at 90°, push back up. Lean more forward for more chest activation.',
        imageUrl: `${WGER}/83/Bench-dips-1.png`,
        tips: '3 × 8–12 reps · Add weight when bodyweight is easy',
      },
      {
        key: 'triceps_corda',
        name: 'Tricep Rope Pushdown',
        muscle: 'Triceps',
        description: 'Stand at cable machine with rope attachment. Keep elbows pinned to sides. Push rope down and spread hands apart at the bottom.',
        imageUrl: `${WGER}/88/Narrow-grip-bench-press-1.png`,
        tips: '4 × 12–15 reps · Elbows must not flare out',
      },
    ],
  },
  {
    day: 'quarta',
    label: 'Wednesday',
    split: 'Legs',
    muscles: 'Quads · Glutes · Hamstrings · Calves',
    exercises: [
      {
        key: 'agachamento',
        name: 'Barbell Back Squat',
        muscle: 'Quads / Glutes',
        description: 'Bar on upper traps, feet shoulder-width apart. Squat until thighs are parallel to floor, keeping knees tracking over toes.',
        imageUrl: `${WGER}/191/Front-squat-1-857x1024.png`,
        tips: '4 × 6–8 reps · King of all exercises',
      },
      {
        key: 'leg_press',
        name: 'Leg Press',
        muscle: 'Quads / Glutes',
        description: 'Feet shoulder-width on platform. Lower sled until knees are at 90°, press back without locking knees at the top.',
        imageUrl: '',
        tips: '4 × 10–12 reps · Foot position changes the focus',
      },
      {
        key: 'stiff',
        name: 'Romanian Deadlift',
        muscle: 'Hamstrings / Glutes',
        description: 'Hold bar or dumbbells in front. Push hips back while lowering weight, feeling hamstring stretch. Keep back flat throughout.',
        imageUrl: `${WGER}/161/Dead-lifts-2.png`,
        tips: '4 × 10 reps · Feel it in hamstrings, not lower back',
      },
      {
        key: 'extensora',
        name: 'Leg Extension',
        muscle: 'Quads',
        description: 'Adjust seat so knees align with machine pivot. Extend fully and hold 1 second at top. Lower with control.',
        imageUrl: '',
        tips: '3 × 12–15 reps · Pause at the top',
      },
      {
        key: 'flexora',
        name: 'Lying Leg Curl',
        muscle: 'Hamstrings',
        description: 'Lying face down, curl weight until heels approach glutes. Keep hips pressed into pad. Lower slowly.',
        imageUrl: `${WGER}/154/lying-leg-curl-machine-large-1.png`,
        tips: '4 × 12 reps · Don\'t let hips rise',
      },
      {
        key: 'panturrilha',
        name: 'Standing Calf Raise',
        muscle: 'Calves',
        description: 'On a step or flat floor, rise onto toes as high as possible. Hold 1–2 seconds at top, lower until full stretch is felt.',
        imageUrl: '',
        tips: '4 × 15–20 reps · Full range of motion',
      },
    ],
  },
  {
    day: 'quinta',
    label: 'Thursday',
    split: 'Pull',
    muscles: 'Back · Lats · Biceps',
    exercises: [
      {
        key: 'barra_fixa',
        name: 'Pull-Up / Lat Pulldown',
        muscle: 'Lats / Upper Back',
        description: 'Overhand grip, wider than shoulders. Pull until chin clears the bar by driving elbows down toward hips. If unable to do pull-ups, use lat pulldown machine.',
        imageUrl: `${WGER}/181/Chin-ups-2.png`,
        tips: '4 × max reps · Use assisted machine if needed',
      },
      {
        key: 'remada_curvada',
        name: 'Bent-Over Barbell Row',
        muscle: 'Mid Back',
        description: 'Hinge at hips until torso is ~45°. Pull bar to lower abdomen, squeezing shoulder blades together. Keep back flat throughout.',
        imageUrl: `${WGER}/110/Reverse-grip-bent-over-rows-1.png`,
        tips: '4 × 8–10 reps · Elbows close to body',
      },
      {
        key: 'puxada_frontal',
        name: 'Lat Pulldown',
        muscle: 'Lats',
        description: 'Wide overhand grip on bar. Pull down to chin level with slight backward lean. Elbows drive down and back — think about pulling with your back, not arms.',
        imageUrl: `${WGER}/143/Cable-seated-rows-1.png`,
        tips: '4 × 10–12 reps · Drive elbows to hips',
      },
      {
        key: 'remada_unilateral',
        name: 'Single-Arm Dumbbell Row',
        muscle: 'Back (unilateral)',
        description: 'Support one knee and hand on bench. Pull dumbbell straight up to hip, fully retracting the shoulder blade. Lower with full control.',
        imageUrl: `${WGER}/109/Barbell-rear-delt-row-1.png`,
        tips: '4 × 10 reps per side · Full range of motion',
      },
      {
        key: 'rosca_direta',
        name: 'Barbell Curl',
        muscle: 'Biceps',
        description: 'Standing, elbows pinned to sides. Curl bar up until forearms are vertical, squeeze at top. Lower fully for complete stretch.',
        imageUrl: `${WGER}/81/Biceps-curl-1.png`,
        tips: '3 × 10–12 reps · Elbows must not move forward',
      },
      {
        key: 'rosca_martelo',
        name: 'Hammer Curl',
        muscle: 'Biceps / Forearm',
        description: 'Neutral grip (thumbs up). Curl alternating or simultaneously, keeping elbows fixed at sides. Also targets brachialis and forearm.',
        imageUrl: `${WGER}/86/Bicep-hammer-curl-1.png`,
        tips: '3 × 12 reps · Great for arm thickness',
      },
    ],
  },
]

export const DAYS_MAP: Record<string, WorkoutDay> = Object.fromEntries(
  WORKOUT_DAYS.map((d) => [d.day, d])
)

export const MOTIVATIONAL_PHRASES = [
  'The only bad workout is the one that didn\'t happen.',
  'Consistency beats perfection every time.',
  'Your future self will thank you.',
  'No shortcuts. Just today\'s workout.',
  'Heavier than yesterday.',
  'The pain fades. The pride stays.',
  'Be the strongest person in the room.',
  'Leg day? Always leg day.',
  'Focus. Strength. Dedication.',
  'Lift more than your excuses.',
]
