import type { WorkoutDay } from '@/types'

export const WORKOUT_DAYS: WorkoutDay[] = [
  {
    day: 'terca',
    label: 'Terça',
    split: 'Push',
    muscles: 'Peito · Ombro · Tríceps',
    exercises: [
      {
        key: 'supino_reto',
        name: 'Supino Reto com Barra',
        muscle: 'Peitoral',
        description: 'Deite no banco, segure a barra na largura dos ombros e pressione até estender os braços. Controle a descida.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Bench_press.gif/220px-Bench_press.gif',
        tips: '4 × 8–10 reps · Cotovelos a 45° do tronco',
      },
      {
        key: 'desenvolvimento_halteres',
        name: 'Desenvolvimento com Halteres',
        muscle: 'Deltóide Anterior',
        description: 'Sentado, com halteres na altura dos ombros, pressione acima da cabeça até os braços estenderem. Abaixe com controle.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Dumbbell_shoulder_press_2.gif/220px-Dumbbell_shoulder_press_2.gif',
        tips: '4 × 10–12 reps · Mantenha o core ativado',
      },
      {
        key: 'crucifixo_inclinado',
        name: 'Crucifixo Inclinado',
        muscle: 'Peitoral Clavicular',
        description: 'Banco inclinado a 30–45°. Com halteres, abra os braços em arco amplo sentindo o alongamento do peitoral. Feche na parte superior.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Incline_Dumbbell_Flyes.gif/220px-Incline_Dumbbell_Flyes.gif',
        tips: '3 × 12 reps · Movimento de abraçar uma árvore',
      },
      {
        key: 'elevacao_lateral',
        name: 'Elevação Lateral com Halteres',
        muscle: 'Deltóide Lateral',
        description: 'Em pé, eleve os halteres lateralmente até a altura dos ombros, com leve flexão no cotovelo. Abaixe lentamente (3 segundos).',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Dumbbell_lateral_raise.gif/220px-Dumbbell_lateral_raise.gif',
        tips: '4 × 15 reps · Descida lenta = mais ganho',
      },
      {
        key: 'dips',
        name: 'Mergulho (Dips)',
        muscle: 'Peitoral Inferior / Tríceps',
        description: 'Nas paralelas, desça até os braços formarem 90° e suba empurrando. Incline o tronco levemente para focar no peitoral.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Chest-dip.gif/220px-Chest-dip.gif',
        tips: '3 × 8–12 reps · Adicione carga se dominar',
      },
      {
        key: 'triceps_corda',
        name: 'Tríceps na Corda (Polia)',
        muscle: 'Tríceps',
        description: 'Na polia alta com corda, mantenha os cotovelos fixos ao lado do corpo e estenda os braços completamente, abrindo as mãos ao final.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Triceps_pushdown_2.gif/220px-Triceps_pushdown_2.gif',
        tips: '4 × 12–15 reps · Cotovelos fixos = isolamento',
      },
    ],
  },
  {
    day: 'quarta',
    label: 'Quarta',
    split: 'Legs',
    muscles: 'Quadríceps · Glúteos · Posterior · Panturrilha',
    exercises: [
      {
        key: 'agachamento',
        name: 'Agachamento Livre com Barra',
        muscle: 'Quadríceps / Glúteos',
        description: 'Barra nos trapézios, pés na largura dos ombros. Desça até as coxas ficarem paralelas ao chão. Joelhos seguem a direção dos pés.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Squat_side_animated.gif/220px-Squat_side_animated.gif',
        tips: '4 × 6–8 reps · Rei dos exercícios',
      },
      {
        key: 'leg_press',
        name: 'Leg Press 45°',
        muscle: 'Quadríceps / Glúteos',
        description: 'Pés na plataforma na largura dos ombros. Desça até 90° de flexão e empurre de volta sem travar os joelhos no topo.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Leg_Press.gif/220px-Leg_Press.gif',
        tips: '4 × 10–12 reps · Posição dos pés muda o foco',
      },
      {
        key: 'stiff',
        name: 'Stiff (Romanian Deadlift)',
        muscle: 'Posterior / Glúteos',
        description: 'Barra ou halteres à frente do corpo. Desça empurrando o quadril para trás, sentindo o alongamento dos isquiotibiais. Mantenha costas retas.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Romanian_deadlift.gif/220px-Romanian_deadlift.gif',
        tips: '4 × 10 reps · Sinta o posterior, não as costas',
      },
      {
        key: 'extensora',
        name: 'Cadeira Extensora',
        muscle: 'Quadríceps',
        description: 'Ajuste o banco para os joelhos alinharem com o eixo da máquina. Estenda completamente e segure 1 segundo no topo. Desça com controle.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Leg_extension.gif/220px-Leg_extension.gif',
        tips: '3 × 12–15 reps · Pausa no topo',
      },
      {
        key: 'flexora',
        name: 'Mesa Flexora (Leg Curl)',
        muscle: 'Isquiotibiais',
        description: 'Deitado na máquina, puxe o peso até o calcanhar tocar a coxa. Volte lentamente. Quadril permanece em contato com o banco.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Leg_curls_lying.gif/220px-Leg_curls_lying.gif',
        tips: '4 × 12 reps · Não balance o quadril',
      },
      {
        key: 'panturrilha',
        name: 'Panturrilha em Pé',
        muscle: 'Gastrocnêmio',
        description: 'No step ou no chão, suba na ponta dos pés o máximo possível e segure 1–2 segundos. Desça até sentir o alongamento completo.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Standing_calf_raise.gif/220px-Standing_calf_raise.gif',
        tips: '4 × 15–20 reps · Amplitude completa',
      },
    ],
  },
  {
    day: 'quinta',
    label: 'Quinta',
    split: 'Pull',
    muscles: 'Costas · Dorsal · Bíceps',
    exercises: [
      {
        key: 'barra_fixa',
        name: 'Barra Fixa (Puxada)',
        muscle: 'Dorsal / Costas',
        description: 'Pegada pronada mais larga que os ombros. Puxe o corpo até o queixo passar da barra, focando em "trazer os cotovelos para o chão".',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Pull_up_2.gif/220px-Pull_up_2.gif',
        tips: '4 × máx reps · Se não aguentar, use a polia',
      },
      {
        key: 'remada_curvada',
        name: 'Remada Curvada com Barra',
        muscle: 'Costas Médias',
        description: 'Tronco inclinado a ~45°. Puxe a barra em direção ao abdômen inferior, contraindo as escápulas. Mantenha as costas retas durante todo o movimento.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Barbell_row.gif/220px-Barbell_row.gif',
        tips: '4 × 8–10 reps · Cotovelos junto ao corpo',
      },
      {
        key: 'puxada_frontal',
        name: 'Puxada Frontal na Polia',
        muscle: 'Dorsal',
        description: 'Na polia alta, pegada aberta pronada. Puxe a barra até a altura do queixo, contraindo o dorsal. Leve inclinação para trás do tronco.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Lat_pulldown.gif/220px-Lat_pulldown.gif',
        tips: '4 × 10–12 reps · Pense em puxar os cotovelos para baixo',
      },
      {
        key: 'remada_unilateral',
        name: 'Remada Unilateral com Haltere',
        muscle: 'Costas (unilateral)',
        description: 'Apoie um joelho e a mão no banco. Com o outro braço, puxe o haltere em linha reta até o quadril, contraindo completamente as costas.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Dumbbell_row.gif/220px-Dumbbell_row.gif',
        tips: '4 × 10 reps por lado · Grande amplitude',
      },
      {
        key: 'rosca_direta',
        name: 'Rosca Direta com Barra',
        muscle: 'Bíceps',
        description: 'Em pé, cotovelos fixos ao lado do corpo. Curve os braços até a barra chegar perto do ombro. Desça completamente para o alongamento.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Barbell_curl.gif/220px-Barbell_curl.gif',
        tips: '3 × 10–12 reps · Cotovelos não se movem',
      },
      {
        key: 'rosca_martelo',
        name: 'Rosca Martelo com Halteres',
        muscle: 'Bíceps / Braquial',
        description: 'Pegada neutra (polegar para cima). Curve alternando ou simultâneo, mantendo os cotovelos fixos ao lado do corpo. Trabalha braquial e antebraço também.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Hammer_curl.gif/220px-Hammer_curl.gif',
        tips: '3 × 12 reps · Ótimo para volume do braço',
      },
    ],
  },
]

export const DAYS_MAP: Record<string, WorkoutDay> = Object.fromEntries(
  WORKOUT_DAYS.map((d) => [d.day, d])
)

export const MOTIVATIONAL_PHRASES = [
  'O único treino ruim é o que não aconteceu.',
  'Consistência bate perfeição toda vez.',
  'Seu futuro eu vai agradecer.',
  'Não existe atalho. Existe o treino de hoje.',
  'Mais pesado que ontem.',
  'A dor passa, o orgulho fica.',
  'Seja a pessoa mais forte da sala.',
  'Dia de perna? Sempre dia de perna.',
  'Foco, força e fé.',
  'Levanta mais do que as desculpas.',
]
